language: node_js
node_js:
  - 12.9.0
cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: heroku
  app: seer-team3
  api_key:
    secure: "Lw/B/Q+Kuy7mvE8FJDuMiBXdf4CMu1qJRbqX57xEctG0I7tIWmX/pUm0buzMDV+sTNdJcNDmw8kx/kBmIGAj1A/PHOnI4l4vh/q3MQYRCQZ0G9CcQRhq44YWAbTGDMSS1kDwD96e9QFV4rQTPo1Q9vfmrQGgrvxOAfkccB+rdhfooV2d8sMPT1orhRgn4WdclVShSls2t9skgApq2hMcQ5pzf94UHRYHs07Yje8Ktawfb7FrzsbfzS8ZaEEY4UmGzP0YXJDtIOzLTYsYsejUYMy6jy5uf+yhKaK+kdaDzunhGnpngG6f+Qh+lnb7OZrHsKrHBmZg/VYVf9lcNywQ0tvPJ8Mr4uMSF/70Iz+hT0HkZJUGOvHIny/ZUcAr0HP3oRXPE8bTqeXHp/H8M+Z6tNtWAVwjzVzVAHL4BJ8XORkd1Ay2I4uBTaPiCtK55zAScRe8T7VMJquR+0XtNpwKSsgEOdJRx4a4wuxS7LSuyAh9Vnp03bTMiniFyFUhQl3HkOuQAVqwJWwEdiKJUObiJx4HgwJpPCdKVAz/rIUCo4EQX4z3kxWrUzczjRSmppBXBlasK8sr83v3dfmAkhauZ+hC42x/mQ9xPF4mKBueEruFxbx2Qj9aAa+QepInWBANLh0XcIhOuNOQlUISBUN6REpzZXliYKrM8HbXxuynrCk="
