language: node_js
node_js:
  - 12.9.0
cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: "lhWB0hz6Y/DEex0OFgmK7s49m774J+VF+P1oEK+RsVXyURaqK9B+6qNP4ljO/shjkHFj0DbIr0VOR4IjGB3CAgIfWpXxVcjuHGIXYHk8IW9HqxelWJfC97yfjPdCpnSM9c5iXnw7LLQlkMXtoogyPDV2oJLrxqbuFSVcQzC54pniEAWwq/Tl0QPQ7w1Eg+GzavnOTSxH1leu1OMsBC3v16Yrj2jeRMkLGDBV5psex0u7GiwmmUJtSYjRUcJi0XiNvz1j51XaJH9FSoRLt2WFDAHmSUCnx93ZpOO8v19s0wK0IkRqsrBQ1u7aIIXTMr3YQWyVPr2/3PUbuhSWayHTZ78N2ZnU3pC79Ea6OxuweBUffLXH9oWHxKLdFC5k0Ztt/1f1VQT7hgh+gWOr9dXM9VwIwhUPE3BcalfoKzjP3+cM2U+x7HE6FANYgNP7crK+yW16sJ71V6SPNUPwXcSG30QjPS1YGygufO69ycaUXuYCKe0f4HWbNkhtp9/Z+fUcCimkQl2BGthD90GwZjq5QsnOxu6cmaNzE9M0gGuzHXIuAKW+H+6jrU4749nDPWHEQEz5nHosOwQMEDmUhz/RamDEayZHOxzOGR91uu5wIhNkiNd/WIa0WNaoDjppCQJaAfFdbcIJCs3RETC5e90H1GbJmDFr3egrj/dj7Tnazbw="
  app: seer-team3
